// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztqatzdqkocgdlfjgusw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cWF0emRxa29jZ2RsZmpndXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjY0ODUsImV4cCI6MjA2ODA0MjQ4NX0.90Fvhmv54pBlJrrgpe1JRPgb6K3BYVAm6DiQW0AS7DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});